/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pets.database;

import lombok.extern.slf4j.Slf4j;
import pets.database.app.server.ServerJetty;

@Slf4j
public class App {
    public static void main(String[] args) throws Exception {
        log.info("Begin pets-database-layer-simple initialization...");
        new ServerJetty().start();
        log.info("End pets-database-layer-simple initialization...");
    }
}
